const fs = require('fs');
const p3 = [
'',
'      <div className="card anim-rise p-6">',
'        <h3 className="font-display text-base font-extrabold">Billing history</h3>',
'        <p className="mt-0.5 text-xs text-ink-400">All subscription payments, upgrades, and renewals. Newest first.</p>',
'        {paymentsLoading ? (',
'          <div className="mt-4 space-y-3">{[1,2,3].map(i => <div key={i} className="h-12 skeleton rounded-xl" />)}</div>',
'        ) : payments.length === 0 ? (',
'          <p className="mt-4 rounded-xl bg-cream-50 px-4 py-6 text-center text-sm font-semibold text-ink-400">No billing activity yet.</p>',
'        ) : (',
'          <div className="mt-4 overflow-x-auto scrollbar-slim"><table className="tbl"><thead><tr><th>Reference</th><th>Tier</th><th>Type</th><th>Amount</th><th>Status</th><th>Date</th><th></th></tr></thead><tbody>',
'            {payments.map(p => (',
'              <tr key={p.id} className="cursor-pointer hover:bg-cream-50"><td><span className="font-mono text-xs font-bold">{p.reference || "—"}</span></td><td>{titleCase(p.tier)}</td><td><Badge tone="neutral">{titleCase(p.kind)}</Badge></td><td className="text-right tabular-nums"><Money v={p.amount} currency="NGN" /></td><td><StatusBadge status={p.status} /></td><td className="text-ink-400 text-xs">{fd(p.createdAt)}</td><td><Button variant="ghost" size="sm" icon="eye" onClick={() => viewPayment(p.id)} title="View details" /></td></tr>',
'            ))}',
'          </tbody></table></div>',
'        )}',
'      </div>',
'',
'      <Modal open={!!selectedPayment} onClose={() => setSelectedPayment(null)} title="Payment details" wide>',
'        {selectedPayment && (',
'          <div className="space-y-4"><div className="grid grid-cols-2 gap-4">',
'            <Field label="Reference"><Input value={selectedPayment.reference || ""} disabled /></Field>',
'            <Field label="Tier"><Input value={titleCase(selectedPayment.tier)} disabled /></Field>',
'            <Field label="Type"><Input value={titleCase(selectedPayment.kind)} disabled /></Field>',
'            <Field label="Status"><Input value={titleCase(selectedPayment.status)} disabled /></Field>',
'            <Field label="Amount"><Input value={selectedPayment.amount || "0.00"} disabled /></Field>',
'            <Field label="Provider ref"><Input value={selectedPayment.providerRef || "—"} disabled /></Field>',
'          </div><div className="grid grid-cols-2 gap-4">',
'            <Field label="Created"><Input value={fd(selectedPayment.createdAt)} disabled /></Field>',
'            <Field label="Paid at"><Input value={fd(selectedPayment.paidAt)} disabled /></Field>',
'          </div>',
'          {selectedPayment.orphanReason && (<div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-sm font-bold text-amber-800">Orphan (no local effect)</p><p className="mt-1 text-xs text-amber-700">{selectedPayment.orphanReason}</p></div>)}',
'          </div>',
'        )}',
'      </Modal>',
'',
'      <div className="card anim-rise p-6">',
'        <h3 className="font-display text-base font-extrabold">Custom domain</h3>',
'        {!flags.customDomain ? (',
'          <p className="mt-2 text-sm text-ink-500">Custom domains are available on <strong>Pro</strong> and <strong>Enterprise</strong>. Upgrade to point your own domain at the storefront.</p>',
'        ) : (',
'          <><p className="mt-1 text-xs text-ink-400">Point a CNAME at your Brikoh storefront, then save the domain here.</p><div className="mt-4 flex flex-wrap items-end gap-3"><div className="min-w-[220px] flex-1"><Field label="Domain"><Input value={domain} onChange={e => setDomain(e.target.value)} placeholder="shop.yourbrand.com" /></Field></div><Button loading={domainBusy} onClick={saveDomain} icon="check">Save domain</Button></div></>',
'        )}',
'      </div>',
'',
'      <p className="text-center text-xs text-ink-400">Caps only block new creates. Existing data is never deleted. Contact support to upgrade.</p>',
'    </div>',
'  );',
].join('\n');
fs.appendFileSync('scripts/plan-body.txt', p3);
console.log('Part 3 appended:', p3.length, 'chars');
console.log('Total template size:', fs.readFileSync('scripts/plan-body.txt', 'utf8').length, 'chars');
